const products = [
    {
        _id: 1,
        title: 'Iphone 13',
        category: '1',
        brand: '1',
        year: 2022,
        prevPrice: '',
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: 'New',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 2,
        title: 'Galaxy note',
        category: '2',
        brand: '2',
        year: 2021,
        prevPrice: '',
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 3,
        title: 'macbook',
        category: '3',
        brand: '1',
        year: 2020,
        prevPrice: 1500,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 4,
        title: 'matebook',
        category: '4',
        brand: '3',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 5,
        title: 'matebook',
        category: '5',
        brand: '3',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 6,
        title: 'matebook',
        category: '6',
        brand: '3',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 7,
        title: 'matebook',
        category: '1',
        brand: '6',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 8,
        title: 'matebook',
        category: '4',
        brand: '5',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 9,
        title: 'matebook',
        category: '5',
        brand: '4',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 10,
        title: 'matebook',
        category: '3',
        brand: '2',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
    {
        _id: 11,
        title: 'matebook',
        category: '3',
        brand: '3',
        year: 2019,
        prevPrice: 1230,
        price: 999,
        rate: 5,
        isFavourite: false,
        tags: '',
        promotion: '',
        description: '',
        configuration: [],
    },
];

const fetchAll = () =>
    new Promise((resolve) => {
        window.setTimeout(function() {
            resolve(products);
        }, 300);
    });

export default {
    fetchAll,
};
